### ISSUE TITLE
[BUG] DBSCAN seems to be broken

### ISSUE THREAD

**Issue by lukasfue** [python-microscopy/python-microscopy#1373]
**Describe the bug**
DBSCAN gives an error when trying to apply it data.
- I used the same data and parameters that have worked in the past and still get the error

**To Reproduce**
1. Go to Analysis > Clustering > DBSCANClump
2. Apply desired parameters
3. See error:
 Error whilst running Analysis>Clustering>DBSCAN Clump
==============================================
python-microscopy=22.01.12[unknown]
python=3.7.9, platform=win32
numpy=1.19.1, wx=4.0.4 msw (phoenix) wxWidgets 3.0.5

Traceback
=========
Traceback (most recent call last):
  File "C:\Users\laf62\.conda\envs\pyme\lib\site-packages\PYME\ui\progress.py", line 153, in func
    return fcn(*args, **kwargs)
  File "C:\Users\laf62\.conda\envs\pyme\lib\site-packages\PYME\LMVis\Extras\clusterAnalysis.py", line 93, in OnClumpDBSCAN
    recipe.add_modules_and_execute([clumper,])
  File "C:\Users\laf62\.conda\envs\pyme\lib\site-packages\PYME\recipes\recipe.py", line 457, in add_modules_and_execute
    self.execute()
  File "C:\Users\laf62\.conda\envs\pyme\lib\site-packages\PYME\recipes\recipe.py", line 203, in execute
    m.execute(self.namespace)
  File "C:\Users\laf62\.conda\envs\pyme\lib\site-packages\PYME\recipes\localisations.py", line 446, in execute
    self.searchRadius, self.minClumpSize)
TypeError: dbscan() takes from 1 to 2 positional arguments but 3 were given

**Expected behavior**
Execution of DBSCAN algorithm

**Screenshots**
This was with 4Pi SMS data that I've applied DBSCAN to before and it worked fine (about 8 months ago)
Here are the parameters I used:
![image](https://github.com/python-microscopy/python-microscopy/assets/36608397/8fa7cda0-4edf-47bd-8435-657a2d0a7496)

**Comment by David-Baddeley** [comment]
Was fixed in https://github.com/python-microscopy/python-microscopy/pull/1201

Upgrading to a more recent PYME version should fix things.

**Comment by lukasfue** [comment]
Hi David,

Git status says I am up to date with PYME, but I still get this error. Could I be outdated on something else possibly?

**Comment by barentine** [comment]
Hey Lukas, sorry for the issue - mind doing a ‘conda list’ and letting us know what version of sklearn you have?

**Comment by lukasfue** [comment]
Hi Andrew, no worries! Thanks for the help. Here's what is says:
"scikit-learn              1.0.2                    pypi_0    pypi"

**Comment by barentine** [comment]
Gotcha, well, David's right that your issue is an out of date version of PYME.

You can tell from your traceback, here:
 `File "C:\Users\laf62.conda\envs\pyme\lib\site-packages\PYME\recipes\localisations.py", line 446, in execute
self.searchRadius, self.minClumpSize)` 
As David mentioned, that line of code was changed in PR #1201, which went into release 23.03.02. You can find a list of releases [here](https://github.com/python-microscopy/python-microscopy/releases). Your git status might not be tracking the main branch of the main pyme, or just hasn't fetched or so - perhaps it is looking at your fork, or Zach's fork? Or you are on a different branch? Regardless, the python-microscopy version you posted is 22.01.12, so whatever environment you're running from is not an updated version of PYME.

I would recommend `git checkout master` followed by `git pull https://github.com/python-microscopy/python-microscopy`, and finally changing to the top directory and re-running `python setup.py develop` (making sure to do that last part in your intended conda environment).

**Comment by csoeller** [comment]
Yes, I'd also guess you need a `git pull` or `git pull master`. I have never fully gotten into the git command line interface and would recommend a GUI interface for like minded users. I am using _gitkraken_ and via the github student/teacher program can access the pro version for free.

P.S. re-running `python setup.py develop` should be only needed when cython extension or similar need rebuilding but this can be hard to tell what has changed and is safe to do at any time.

**Comment by lukasfue** [comment]
Thanks all for the tips. I was up-to-date with master in the github repo. However, when I launched Visgui, it was apparently running off an an older version of PYME somehow. I'm not sure if I have another repo of PYME that's interfering somehow. So, I decided to reinstall but now I'm having issues with that. I get the following traceback when trying to launch Visgui after reinstallation:

Traceback (most recent call last):
  File "C:\Users\laf62\.conda\envs\pyme\Scripts\VisGUI-script.py", line 33, in <module>
    sys.exit(load_entry_point('python-microscopy', 'console_scripts', 'VisGUI')())
  File "C:\Users\laf62\.conda\envs\pyme\Scripts\VisGUI-script.py", line 25, in importlib_load_entry_point
    return next(matches).load()
  File "C:\Users\laf62\.conda\envs\pyme\lib\site-packages\importlib_metadata\__init__.py", line 203, in load
    module = import_module(match.group('module'))
  File "C:\Users\laf62\.conda\envs\pyme\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "c:\users\laf62\code\python-microscopy\PYME\LMVis\VisGUI.py", line 47, in <module>
    from PYME.LMVis import pipeline
  File "c:\users\laf62\code\python-microscopy\PYME\LMVis\pipeline.py", line 24, in <module>
    from PYME.IO import tabular
  File "c:\users\laf62\code\python-microscopy\PYME\IO\tabular.py", line 37, in <module>
    import tables
  File "C:\Users\laf62\.conda\envs\pyme\lib\site-packages\tables\__init__.py", line 93, in <module>
    from .utilsextension import (
ImportError: DLL load failed: The specified module could not be found.

Does anybody have an idea of what this is about? I've done this reinstallation process many times with no issues before.

**Comment by David-Baddeley** [comment]
How did you install the base environment? conda? pip? My guess is that the pytables package didn't bundle the HDF5 libraries. This shouldn't be an issue for the conda package, but could be for a pip install (which might assume the libraries were already installed as would often be the case on Mac or Linux).

**Comment by David-Baddeley** [comment]
should add that `git status` generally tells you if you have any uncommitted local changes, not if there are any upstream changes.

**Comment by lukasfue** [comment]
I used "conda create -n pyme pyme-depends python=3.7". Before uninstalling, entering `git pull` or `git status` said I was up to date with the python-microscopy master branch.

**Comment by csoeller** [comment]
I am not sure if you are familiar with the conda version of Python virtualenvs which we use heavily to make various PYME installs that do not interfere with each other. We highly recommend this approach and we just then have launcher scripts to launch the various PYME apps from the suitable conda environment. The approach is described in [Installing-PYME-with-py3-win10](https://github.com/csoeller/pyme-install-docs/blob/master/Installing-PYME-with-py3-win10.md) and a brief doc on [making suitable windows launchers](https://github.com/csoeller/pyme-install-docs/blob/master/PYME-windows-launchers.md).

That way you can make installs based on different Python versions, experimental installs from different git branches etc and also try a new install without wiping an existing install.

Perhaps this is overkill for you and possibly may seem even more confusing, it all depends on personal pereferences.

**Comment by csoeller** [comment]
PS - I see you do use named environments but wonder if you keep several around. That is were switching between envs can become useful.

**Comment by David-Baddeley** [comment]
@lukasfue - That implies you have a conda package for pytables, which should have included the HDF5 libraries. The corollary is that the specific version of the package that you have installed is broken. My suggestion:

- do a `conda list` to determine which version of pytables you have  (it would also be interesting to know if it is from the main anaconda channel(s) or from conda-forge)
- install a different (likely earlier version) - `conda install pytables=x.x`. Repeat until you find one that works.

If this problem is reproducible, we might need to pin pytables in pyme-depends to ensure that we get a good one.

**Comment by lukasfue** [comment]
@David-Baddeley - I ended up installing pytables=3.7, and I was able to then launch visgui without issue and DBSCAN worked in the fresh install, so I suppose the original problem was somehow related to my previous installation. With that said, it seems that maybe the pytables dependency needs updating? Whatever it's currently set to doesn't seem to work since Yujin and I (both my PC and Macbook) had this issue when trying to install PYME, but updating pytables to 3.7 resolved it in all cases.
